"""added new column

Revision ID: 937e71f6d0af
Revises: ed4b34331142
Create Date: 2026-01-22 05:11:06.804326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937e71f6d0af'
down_revision = 'ed4b34331142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
